# Identity Server configuration
# Email configuration for "192.168.2.102"
is:
  email:
    sender-name: "The Things Stack"
    sender-address: "noreply@192.168.2.102"
    network:
      name: "The Things Stack"
      console-url: "https://192.168.2.102/console"
      identity-server-url: "https://192.168.2.102/oauth"

  # Web UI configuration for "192.168.2.102":
  oauth:
    ui:
      canonical-url: "https://192.168.2.102/oauth"
      is:
        base-url: "https://192.168.2.102/api/v3"

# HTTP server configuration
http:
  cookie:
    block-key: "" # generate 32 bytes (openssl rand -hex 32)
    hash-key: "" # generate 64 bytes (openssl rand -hex 64)
  metrics:
    password: "metrics" # choose a password
  pprof:
    password: "pprof" # choose a password

# If using custom certificates:
tls:
  source: file
  root-ca: /run/secrets/ca.pem
  certificate: /run/secrets/cert.pem
  key: /run/secrets/key.pem

# Let's encrypt for "192.168.2.102"
# tls:
#   source: acme
#   acme:
#     dir: /var/lib/acme
#     email: "you@192.168.2.102"
#     hosts: ["192.168.2.102"]
#     default-host: "192.168.2.102"

# If Gateway Server enabled, defaults for "192.168.2.102":
gs:
  mqtt:
    public-address: "192.168.2.102:1882"
    public-tls-address: "192.168.2.102:8882"
  mqtt-v2:
    public-address: "192.168.2.102:1881"
    public-tls-address: "192.168.2.102:8881"

# If Gateway Configuration Server enabled, defaults for "192.168.2.102":
gcs:
  basic-station:
    default:
      lns-uri: "wss://192.168.2.102:8887"

# Web UI configuration for "192.168.2.102":
console:
  ui:
    canonical-url: "https://192.168.2.102/console"
    account-url: "https://192.168.2.102/oauth"
    is:
      base-url: "https://192.168.2.102/api/v3"
    gs:
      base-url: "https://192.168.2.102/api/v3"
    ns:
      base-url: "https://192.168.2.102/api/v3"
    as:
      base-url: "https://192.168.2.102/api/v3"
    js:
      base-url: "https://192.168.2.102/api/v3"
    gcs:
      base-url: "https://192.168.2.102/api/v3"
    qrg:
      base-url: "https://192.168.2.102/api/v3"
    edtc:
      base-url: "https://192.168.2.102/api/v3"
    dcs:
      base-url: "https://192.168.2.102/api/v3"
  oauth:
    authorize-url: "https://192.168.2.102/oauth/authorize"
    token-url: "https://192.168.2.102/oauth/token"
    logout-url: "https://192.168.2.102/oauth/logout"
    client-id: "console"
    client-secret: "console" # choose or generate a secret

# If Application Server enabled, defaults for "192.168.2.102":
as:
  mqtt:
    public-address: "192.168.2.102:1883"
    public-tls-address: "192.168.2.102:8883"
  webhooks:
    downlink:
      public-address: "192.168.2.102:1885/api/v3"

# Managed gateway configuration, defaults for "192.168.2.102".
# This configures a connection with The Things Gateway Controller, a service operated by The Things Industries.
# This allows connecting, for example, The Things Indoor Gateway Pro.
ttgc:
  enabled: true
  domain: 192.168.2.102
  # Let's Encrypt:
  # tls:
  #   source: acme
  # If using custom certificates:
  tls:
    source: file
    certificate: /run/secrets/cert.pem
    key: /run/secrets/key.pem