# Configuración Global del Agente
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = "telegraf-docker"
  debug = true

# -------------------------------------------------------------------------
# INPUT: MQTT
# -------------------------------------------------------------------------
[[inputs.mqtt_consumer]]
  #servers = ["tcp://mosquitto:1883"]   # servidor para pruebas locales
  servers = ["tcp://192.168.137.28:1883"]

  topics = ["v3/my-primer-aplicacion/devices/esp-segunda-prueba/up"]  
  
  username = "my-primer-aplicacion"

  password = "NNSXS.MGGNEZZL7SV6JMNM4MX5ZUFVRW7PE2QHQQ2MLEA.WNDYVVPDRM4AE5HGOWXHBWETYB6JSU2LHF2GGEXC2GFDS45DIRWA"

  data_format = "json_v2"

  [[inputs.mqtt_consumer.json_v2]]
    # (Opcional) Si quieres usar el device_id como etiqueta (tag) para diferenciar dispositivos
    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "end_device_ids.device_id"
      rename = "device_id"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "uplink_message.decoded_payload.temperature_1"
      rename = "temperature_1" # El nombre con el que se guardará en la DB
      type = "float"
# -------------------------------------------------------------------------
# OUTPUT: InfluxDB v2
# -------------------------------------------------------------------------
[[outputs.influxdb_v2]]
  # URL interna del contenedor de InfluxDB
  urls = ["http://influxdb:8086"]

  # El token definido en el docker-compose
  token = "mi-super-token-seguro-unrc"

  # Organización y Bucket solicitados
  organization = "unrc"
  bucket = "lora_bucket"
