# Configuración Global del Agente
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = "telegraf-docker"

# -------------------------------------------------------------------------
# INPUT: MQTT
# -------------------------------------------------------------------------
[[inputs.mqtt_consumer]]
  # URL del broker. Si usas el del docker-compose es "tcp://mosquitto:1883"
  # Si es externo, pon la IP de tu broker, ej: "tcp://192.168.1.50:1883"
  servers = ["tcp://mosquitto:1883"]

  # El tópico donde escuchará los mensajes LoRA
  topics = [
    "lora/datos/#"
  ]

  # Configuración de formato de datos
  data_format = "json"
  
  # Si el JSON es plano como { "sensor_temperatura": 30.2 },
  # Telegraf creará un Field llamado "sensor_temperatura" con valor 30.2.
  
  # Opcional: Agregar tags adicionales para identificar la fuente
  [inputs.mqtt_consumer.tags]
    origen = "network_server"

# -------------------------------------------------------------------------
# OUTPUT: InfluxDB v2
# -------------------------------------------------------------------------
[[outputs.influxdb_v2]]
  # URL interna del contenedor de InfluxDB
  urls = ["http://influxdb:8086"]

  # El token definido en el docker-compose
  token = "mi-super-token-seguro-unrc"

  # Organización y Bucket solicitados
  organization = "unrc"
  bucket = "lora_bucket"
